runtime! debian.vim     " Load Debian defaults
syntax on               " Enable syntax highlighting
set background=dark     " Use dark terminal background
set showcmd             " Show (partial) command in status line.
set showmatch           " Show matching brackets.
set ignorecase          " Do case insensitive matching
set smartcase           " Do smart case matching
set incsearch           " Incremental search
set autowrite           " Automatically save before commands like :next and :make
set hidden              " Hide buffers when they are abandoned
set mouse=a             " Enable mouse usage (all modes)
set tabstop=8           " Tab width
set expandtab           " Use spaces instead of tabs
set shiftwidth=4        " Indent width
set softtabstop=-1      " Soft tab width (spaces) (use shiftwidth)
set number              " Show line numbers
set relativenumber      " Show relative line numbers
set nowrap              " Disable line wrapping
set sidescrolloff=8     " Keep 8 columns from screen edges

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" Jump to the last position when reopening a file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Load indentation rules and plugins according to the detected filetype.
filetype plugin indent on

" Use system clipboard (need +clipboard)
set clipboard=unnamedplus

" Use filetype-specific indentation settings
augroup filetype_indent
  autocmd!
  autocmd FileType c,make setlocal noexpandtab shiftwidth=8
  autocmd FileType vim,sh,toml,yaml,json,html,css
        \ setlocal expandtab shiftwidth=2
augroup END
