runtime! debian.vim     " Load Debian defaults
syntax on               " Enable syntax highlighting
set background=dark     " Use dark terminal background
set showcmd             " Show (partial) command in status line.
set showmatch           " Show matching brackets.
set ignorecase          " Do case insensitive matching
set smartcase           " Do smart case matching
set incsearch           " Incremental search
set autowrite           " Automatically save before commands like :next and :make
set hidden              " Hide buffers when they are abandoned
set mouse=a             " Enable mouse usage (all modes)
set tabstop=8           " Tab width
set softtabstop=4       " Soft tab width (spaces)
set shiftwidth=4        " Indent width
set expandtab           " Use spaces instead of tabs
set number              " Show line numbers
set relativenumber      " Show relative line numbers

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" Jump to the last position when reopening a file
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Load indentation rules and plugins according to the detected filetype.
filetype plugin indent on

" Use system clipboard (need +clipboard)
set clipboard=unnamedplus 
